### ISSUE TITLE
ANALYSIS: Allow users to suggest an entity for 'deletion' or 'merging'

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#168]
related #167

**Comment by kconn** [comment]
I think this should probably be split into several cards: approval queue; request merge button; request delete button; some kind of notification when merge or delete happens. More thoughts on each below.

**queue for merge**

higher-level (for now, admin) users are presented with a merge approval queue that is basically a table of requests, and a second table of past requests (could be same or separate pages; could also use filters on one table, instead of having two separate ones). each row on the approval queue shows the two entities that are requested to be merged, the time requested, the user who requested (with a link to their user page), links to either approve or deny the request. when admin user clicks deny, the request is denied and it is moved to the past requests table. when admin user clicks approve, they are cycled through existing merge process.

**queue for delete**

this differs a bit in that users are able to request deletes for entities, relationships, lists (anything else). These can all appear in same table. for each row, user can see entity, list, or relationship being requested for deletion, time requested, username and link to user page, links to either approve or deny request. 

** request/mark for merge button **

all merge buttons/links on site could be changed to this, for all users. there should be instructions that pop up when you hover over it. when requested it should flash message that it is being entered into deletion queue.

** request/mark for delete button **

all delete buttons could eventually be changed to this and appear for all users (signed-in, presumably). there should be instructions that pop up when you hover over it. when requested it should flash message that it is being entered into deletion queue.

** notifications **

on dashboard, if request is approved? or all requests and their status could be showed?

**Comment by kconn** [comment]
also, i wonder if users should have option of adding note when they request for merge or delete (that admins see), and admins should have option of adding note when they approve or deny?

**Comment by aguestuser** [comment]
some questions (which let's talk about in person):

* why is it valuable to you to have a table both for pending and completed merges? (to evaluate the reliability of a user based on past requests?) how damaging would it be to your expected use of this tool to omit that feature?
* you specify above that **all** merge and delete buttons would become "mark for merge/delete" buttons. does that you don't want admins to be able to delete/merge direclty anymore? ie: that for an admin, the workflow for deleting an entity would be to (1) mark the entity for deletion, (2) navigate to the deletion queue, (3) approve deletion of the entity in question from the queue? happy to build it that way, but would you not perhaps find it cumbersome to have to take 3 steps to perform an action that currently only requires one?
* i like the idea of users providing notes to justify why they made a request and admins providing notes as to why they approved or rejected. should these notes be required or optional? friendly ammendment: let's send an email to the user notifying them of the approval/denial of their request along with the note?
* to make this feature a bit more compartmentalized, i'd propose that we cut it *further* into 2 phases (which i will describe in a comment below, since it's sort of its own thing.)

**Comment by aguestuser** [comment]
proposal for cutting user-requested-actions into phases:

## phase 1: bare bones email review

### 1.1: deletions
* any signed in user may request that an entity/list/relationship (let's call it a "deletable resource") [1] be deleted by clicking a button on its display page
* after the user clicks the button:
  * a popup appears telling them that their request has been forwarded to littlesis admins
  * an email is sent to all admins with a link to a deletion review page, which contains information pertinent to deleting a **single deletable resource** ( this would be: (1) timestamp of request, (2) a link to the resource, username (linked to user profile page), and approve/deny buttons (the elements of the table rows you listed above)

### 1.2: merges
* any signed in user may request that an entity be merged by clicking a button on its display page
* when they click such a button, they will go through the same merging process as admins, with the difference that at the final step (the review merge page), the "merge" button will be a "request merge" button. 
* when the user clicks the "request merge" button:
  * a pop-up appears informing them that their request has been sent to littlesis admins
  * an email will be sent to all admins with a link to a "merge review" page
* when an admin clicks on the link in their email, they will see the same content that the user who requested the merge saw on the merge review page, plus: buttons for approving or denying the merge

## phase 2: add review queue

* admins receive email notifications about user requests as before, except the links in the emails go to a "user request review" page (or maybe they don't receive an email anymore at all?)
* this is a combined list of requested deletes and merges
* each row contains timestamp, username (with link), approve/deny buttons and (in case of deletion) link to "deletable" profile page or (in case of merging) link to merge review page

## phase 3: add notifications/justifications

* when a user marks a resource for merging or deletion, they are prompted to enter a note justifying their request
* this note is included in the review queue
* when the admin approves or denies a request for deletion or merging, they are prompted to enter a note justifying their action
* after a request is approved or denies, the user who made it receives an email notifying them of the response and containing the justification note entered by the admin in the above step

-------------------

[1] you gloss this with "or anything else" above. i'd propose that we make a finite list of what can be deleted.

**Comment by aguestuser** [comment]
closing, as analysis is complete, and has produced the following cards: #442, #443 , #444, #445, #446, #447 , #448 (making up the [user-requests-queue epic](https://github.com/public-accountability/littlesis-rails/labels/user-request-queue))
