### ISSUE TITLE
SPIKE: Donation matching search not turning up expected results [1]

### ISSUE THREAD

**Issue by kconn** [public-accountability/littlesis-rails#222]
There should definitely be matches for this guy in both federal and NYS data: https://littlesis.org/person/77037/Dennis_R_McCoy

There should be more matches for this guy in NYS data:
https://littlesis.org/person/7498/Robert_G_Wilmers

**Comment by kconn** [comment]
This one too, for NYS – https://littlesis.org/entities/140349-Rich_Binko/match_ny_donations
could be because it was searching Rich, not Richard. I added Richard as a new alias but maybe results don't update?

**Comment by kconn** [comment]
This search should be pulling up the "New Yorkers for a Balanced Albany" PAC but it's not: https://littlesis.org/nys/pacs/new?entity=184353&query=new%20yorkers%20for%20a%20balanced

**Comment by kconn** [comment]
This search should be pulling up NYS Senate Republican Campaign Committee: https://littlesis.org/nys/pacs/new?entity=118411&query=senate%20republican

**Comment by aepyornis** [comment]
- [ ] dennis mccoy
- [ ] wilmers
- [ ] rich binko
- [ ] balanced albany
- [ ] NYS SRCC

**Comment by aepyornis** [comment]
We found the "NYS Senate Republican Campaign Committee" but it's listed as a "PARTY STATE"  (committee type code 5) instead of a PAC, which is why it does not show up in the PAC search results, which only include entities of a finite set of committee types. 

We decided not to include entities with committee type 5 because it would imply that we should also include entities of a whole other set of committee types ("county party", "constituted county", etc..). Since we don't fully understand all these encodings and fear that including them might render our data model inaccurate, we decided to pull in "PARTY STATE" entities at this time.

Pending an investigation into these codes, we'll come up with a fix for it in a *subsequent* card, but are descoping that fix from this card.
