### ISSUE TITLE
tag editing restricted by permission [3]

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#233]
# Acceptance Criteria

* buffalo tag my only be added/removed by LS staff
* philadelphia tag may only be added/removed by Molly
* all other tags can be edited by anyone
* in tag edit mode, uneditable tags will be marked as disabled (greyed out? lock?)

# Definitions

* a tag may be open or closed
* if closed, it may only be edited by whitelisted users

# Implementation Notes

* `tags.yml` must now include an `access` field for every tag

* API for tag permissions checking will be something like:

 ```ruby
some_user.permissions.can_tag?("philly")
```
* to accomplish whitelisting, we will store a list of tag ids that any given user may edit, according to (something like) the following schema in the (new) `user_permissions` table:

| user_id | resource_type | access_rules  |
|--|--|--|
| 1           | "List"                | NULL                          | # indicates user 1 is a 'lister'
| 2           | "Tagging"         | "{ tag_ids: [ 1, 2, 3] }" | # indicates user 2 can tag ids w/ tag_id 1, 2, & 3

(which indicates user 1 is a "lister" and user 2 can tag id's w/ `tag_id` == 1, 2, or 3)

**Comment by aguestuser** [comment]
Some random notes from @aepyornis /@aguestuser chat about this today:


* try declaring type of `user_permissions.data` field to be `:json` as first pass in migration to see if it's smart enough to not let you
* then use REALLY big char limit on string column, like [this](https://github.com/public-accountability/littlesis-rails/blob/master/db/migrate/20170508151516_create_pages.rb#L6)
* comment liberally to make clear we're using a **rails** user not a symphony user
* creating `UserPermission` active record class will likely necessitate renaming `UserPermissions` module. let's think about that and circle back. (do we want `Permissions::UserPermissions` instead of `UserPermissions::Permissions`? or something altogether different?)
* TODO: make card for admins editing user tagging permissions
* modify tags.yml to store "open/closed"

**Comment by aguestuser** [comment]
sketch of ultimate desired permissions interface

```ruby
# Permission = Struct.new(:viewable, :editable, :configurable)
user.permissions_for(object) # => Permission
user.has_role?(:lister) # => Boolean
```

**Comment by aguestuser** [comment]
sketch of ultimate desired permissions interface

```ruby
# Permission = Struct.new(:viewable, :editable, :configurable)
user.permissions_for(object) # => Permission
user.has_role?(:lister) # => Boolean
```
