### ISSUE TITLE
more options for sorting entities on lists

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#258]
```
sort by amount donated  ($)

Type: Feature Request

Page: https://littlesis.org/lists/41-all-members-of-congress-since-1981/members

Description
============
alphabetical lists are entirely arbitrary, and only helpful if I'm looking for a name (even then, I'd just search...)

please sort by $ or possibly "# of connections" or a more valuable indicator than A-Z
```

**Comment by robjlucas** [comment]
I've implemented this in https://github.com/public-accountability/littlesis-rails/pull/1189

... but I wonder if some list option should determine whether or not to show this column, since it seems inappropriate on some lists. What do you think @aepyornis ?

E.g.:

![Screenshot from 2020-08-06 13-56-28](https://user-images.githubusercontent.com/25692779/89534434-d5f3cd80-d7ec-11ea-91fd-e7e304445522.png)

**Comment by aepyornis** [comment]
I like the idea of that column being configurable; it would be nice for there to be a way to set the default ordering. of that table.

**Comment by robjlucas** [comment]
> I like the idea of that column being configurable; it would be nice for there to be a way to set the default ordering of that table.

Cool, well let's add that into the current PR before merging it on Thurs.
