### ISSUE TITLE
History page attributes edits to another analyst

### ISSUE THREAD

**Issue by mooninmyname** [public-accountability/littlesis-rails#552]
<img width="1045" alt="screen shot 2018-02-27 at 9 45 53 am" src="https://user-images.githubusercontent.com/35738250/36735342-f3c203f2-1ba3-11e8-916f-1eedcb6ffb3d.png">

Edit made by Kevin is attributed to Munira on entity's history page.

**Comment by aepyornis** [comment]
there are two related callbacks in `Relationship` that seem to be the likely source for this.

[update_entity_timestamps](https://github.com/public-accountability/littlesis-rails/blob/entity-resolution/app/models/relationship.rb#L467-L489) and [update_entity_links](https://github.com/public-accountability/littlesis-rails/blob/entity-resolution/app/models/relationship.rb#L547-L550)

update_entity_links call [update_link_count[(https://github.com/public-accountability/littlesis-rails/blob/entity-resolution/app/models/entity.rb#L721-L723):

``` rb
def update_link_count
  update(link_count: links.count)
end
```

**Comment by aepyornis** [comment]
the issue relates to merging entities.

when someone merges entities, the person who approves the merging is considered the user in PaperTrail, instead of the person who requested the merge.
'
additionally, merging  relationship doesn't seems correctly update the last_user_id of associated entities.

**Comment by aepyornis** [comment]
closing this..it should be resolved by now.
