### ISSUE TITLE
Allow lists to be created without a source link

### ISSUE THREAD

**Issue by aepyornis** [public-accountability/littlesis-rails#718]

**Comment by climatebrad** [comment]
Not sure about this - seems better to keep this as mandatory imho

**Comment by kconn** [comment]
> Not sure about this - seems better to keep this as mandatory imho

@climatebrad agree that being solid on requiring references is good, and I'm a bit torn. in my experience some lists are created when users want to create collections of entities that aren't necessarily sourced to something – for instance, in the past I've made lists of entities related to particular campaigns, and there isn't really a source link for it, so I hack it. we could either leave it that this needs to be hacked or add something like the following:

- still require a reference link (since most lists, eg Forbes billionaires or what have you, have some kind of link)
- check a box if you are creating a custom list of entities with no external sourcing – for instance for a collection of entities you are personally keeping an eye on (reference link wouldn't be required if you check the box)

**Comment by aepyornis** [comment]
To get around the url requirement, users have used _littlesis.org_ as the source link on over 200 lists
